vpc_name                = "eks_vpc_dev"
cidr                    = "10.0.0.0/16"
aws_region              = "us-east-1"
public_subnets          = [ "10.0.101.0/24", "10.0.102.0/24" ]
private_subnets         = [ "10.0.1.0/24", "10.0.2.0/24" ]
azs                     = [ "us-east-1a", "us-east-1b" ]
cluster_name            = "eks-auto-demo"
eks_version             = "1.31"
profile                 = "joshi" # Configure profile or authentication as required.