name: Infrastructure Provisioning Terraform

on:
  push:
    branches:
      - main
      - dev
      - test

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: us-east-1 # Set the appropriate AWS region

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set branch name
        run: echo "BRANCH_NAME=$(basename $GITHUB_REF)" >> $GITHUB_ENV

      - name: Select Terraform directory
        run: |
          if [ "$BRANCH_NAME" == "main" ]; then
            echo "TF_DIR=Environments/prod" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "dev" ]; then
            echo "TF_DIR=Environments/dev" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "test" ]; then
            echo "TF_DIR=Environments/test" >> $GITHUB_ENV
          else
            echo "Unknown branch, exiting."
            exit 1
          fi

      - name: Debugging
        run: |
          echo "Branch Name: $BRANCH_NAME"
          echo "Terraform Directory: $TF_DIR"

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: |
          cd $TF_DIR
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd $TF_DIR
          terraform plan

