name: Infrastructure Provisioning Terraform

on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  setup-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI Profile
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile joshi
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile joshi
          aws configure set region ${{ secrets.AWS_REGION }} --profile joshi
          
      - name: Set AWS Profile Environment Variable
        run: echo "AWS_PROFILE=joshi" >> $GITHUB_ENV

      - name: Create an S3 Bucket
        run: aws s3 mb s3://my-unique-bucket-name
