name: Configure AWS Profile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS CLI profile
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} --profile joshi
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }} --profile joshi
          aws configure set region ${{ secrets.AWS_REGION }} --profile joshi

      - name: Verify AWS Profile Configuration
        run: |
          aws sts get-caller-identity --profile joshi
