name: Infrastructure Provesioning Terraform 
on: 
  push:
    branches: 
      - main
      - dev
      - test


env: 
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs: 
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 
      - name: Output the branch name
        run: | 
          echo $(echo $GITHUB_REF | cut -d'/' -f 3)
          if: $HITHUB_REF == 'main'
            echo "main branch"
